# A string used to differentiate different projects.
# It's recommended to use a unique identifier for each project.
project_id = "invoice-management-system"

[api]
# Port to use for the API URL.
port = 54321

# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
schemas = ["public", "graphql_public"]

# Extra schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# The public schema is already included by default.
# extra_schemas = [""]

# The maximum number of rows returns from a view, table, or stored procedure. Limits to 1000 by default.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322

# The database major version to use. Must be 14 or 15 at the moment.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing
# Use a test email account to avoid spamming your personal email during development.
[inbucket]
port = 54324

# Storage testing
# Use a test storage bucket to avoid cluttering your personal storage during development.
[storage]
# The maximum file size allowed for uploads in MB.
file_size_limit = 50

# Auth testing
# Use a test auth user to avoid cluttering your personal auth during development.
[auth]
# The base URL of your app. It's used to generate email links and redirects.
site_url = "http://localhost:3000"

# A list of URLs that are allowed to redirect to after authentication.
additional_redirect_urls = ["https://localhost:3000"]

# How long tokens are valid for before they need to be refreshed.
jwt_expiry = 3600

# The number of seconds to wait before checking for verification.
refresh_token_rotation_enabled = true

# Enable debug mode to see additional logs.
security_refresh_token_reuse_interval = 10

# Enable debug mode to see additional logs.
security_update_password_require_reauthentication = true

[analytics]
# Port to use for the analytics API.
port = 54327

# The Google Analytics tracking ID.
# This can be left blank if you don't want to use Google Analytics.
# tracking_id = ""

# Enable debug mode to see additional logs.
# debug = false

# Edge Functions
[edge_runtime]
# The port to use for the Edge Functions API.
port = 54321

# The directory to store your Edge Functions.
# This is relative to the root of your project.
# functions_dir = "./supabase/functions"